[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
build_flags = -D BOARD_HAS_PSRAM
board_upload.flash_size = 16MB
upload_speed = 500000
monitor_speed = 115200
debug_tool = esp-builtin
debug_init_break = break setup
build_type = debug
lib_deps = espressif/esp32-camera@^2.0.4
 